Remove /server_time 0proxy dependency
0chain/js-client-sdk pull request #108
Opened 2022-03-24 18:40 UTC by shaktals

As per slack [convo](https://0chain.slack.com/archives/C023KRDU2BU/p1648139681518019) on explorer channel.

2022-03-25 14:16 UTC, cnlangzi requested changes

2022-03-25 19:03 UTC, shaktals commented on index.js
> +    const ts = Math.floor(new Date().getTime() / 1000);
Looking at https://github.com/papio/ntp.js, you can see their lib is not compatible with our application.

Besides, this would couple our services with third party dependencies. If the blockchain really picks-up, that could present many problems.

Also, we are deprecating js-client-sdk and not using it on the new web apps.

We might build a new SDK later, when a better architecture might present itself though experience developing some production grade applications.

For now I say we just let it be.

2022-03-26 05:29 UTC, cnlangzi approved these changes

2022-03-26 05:29 UTC, cnlangzi approved these changes

2022-03-26 05:30 UTC, cnlangzi commented on index.js
> +    const ts = Math.floor(new Date().getTime() / 1000);
I think we should add /servertime on miners instead of 0box.

2022-03-27 15:19 UTC, merged