Fetching Nonce from getBalance
0chain/js-client-sdk pull request #117
Opened 2022-04-23 07:56 UTC by adityamatt

- [todo] Caching of nonce

2022-04-23 08:09 UTC, adityamatt commented
@shaktals  not sure who I should request to review the PR, can you tag the relevant person for review ?

2022-04-23 21:12 UTC, shaktals commented
I can review it

2022-04-23 21:22 UTC, shaktals requested changes
Looks good, before we merge and publish we need to:

- upgrade the lib version on package,json
- test this update with the related block-explorer updates, to confirm it all works together nicely

2022-04-23 21:22 UTC, shaktals commented on index.js
> -    getBalance: (client_id) => {
Any specific reason to move the getBalance method?

2022-04-23 21:22 UTC, shaktals commented on index.js
> +
```suggestion
```

2022-04-23 21:22 UTC, shaktals commented on index.js
> +    const nonceToUse = cachedNonce+1
```suggestion
    }

    const nonceToUse = cachedNonce+1
```

2022-04-23 21:22 UTC, shaktals commented on index.js
> +    if (cachedNonce === undefined) {
```suggestion

    if (cachedNonce === undefined) {
```

2022-04-23 21:22 UTC, shaktals commented on index.js
> +const cachedNonceTime = 5*60*1000       //5 Minutes into milli seconds
A more descriptive variable name would be something like:

```suggestion
const cachedNonceResetInterval = 5*60*1000       //5 Minutes into milli seconds
```

2022-04-23 21:22 UTC, shaktals commented on index.js
> +},cachedNonceTime)
```suggestion
}, cachedNonceTime)

```

2022-04-24 13:56 UTC, adityamatt commented on index.js
> -    getBalance: (client_id) => {
I need to use getBalance to get the nonce to initialize, hence had to move it outside

2022-04-24 14:04 UTC, adityamatt commented
> * test this update with the related block-explorer updates, to confirm it all works together nicely

We don't need any changes in block-explorer as explained here [Comment](https://github.com/0chain/block-explorer/issues/639#issuecomment-1107439165)

2022-04-25 15:08 UTC, adityamatt commented
@cnlangzi  I think the zcn.wasm has some error. Following error is thrown
![image](https://user-images.githubusercontent.com/33998232/165117418-d72da04e-5faf-4622-a935-f9c0e4c56ec5.png)

Steps to Reproduce :
- clone js-client-sdk locally and switch to this branch
- clone block-explorer and npm link the js-client-sdk local repo to be used by block-explorer
- Run and try uploading the file

Based on the error messages thrown. Do you think this is something thats coming from zcn.wasm

2022-04-25 20:26 UTC, shaktals approved these changes
lgtm

2022-04-25 20:29 UTC, shaktals commented
@adityamatt remember that to run the `nonce` feature, you need to use the `hightps-2.devnet-0chain.net` network. 

I just did several file operations there, and everything seems to be working perfectly.

Now we just have to coordinate with @dabasov before we merge this and update all main networks.

My suggestion is to migrate one at a time.

2022-04-26 10:04 UTC, adityamatt commented
aah. I was told to use alpha.devnet. 
Thanks for taking care of it.
@dabasov You can start updating the network I think.

2022-05-10 17:02 UTC, shaktals commented
> @shaktals the PRs for nonce in backend is merged as per @dabasov . I think we can merge this now. But I think we'll also have to update the block-explorer package.json file to use the latest version of js-client-sdk or that happens automatically ?

Yeah, let's wait for @dabasov to confirm here that we are ready to go.
As for how NPM works, I've answered your question before, please research, very easy to find out.

2022-05-12 08:47 UTC, merged