added GMT timezone for any transaction
0chain/js-client-sdk pull request #64
Opened 2021-11-13 06:44 UTC by Sarthakbunny

Added a GMT timezone to be called instead of machine local time.

2021-11-13 16:40 UTC, shaktals approved these changes
Just need to fix the variable name, as the Pacific Time zone is GMT -8.

2021-11-13 16:40 UTC, shaktals commented on index.js
> +    const timeJson =  await pacificZoneTime.json();
```suggestion
    const gmtTime = await fetch('http://worldtimeapi.org/api/timezone/Europe/London');
    const timeJson =  await gmtTime.json();
```

2021-11-13 16:43 UTC, shaktals commented
Ah, also, whenever you update `js-client-sdk` you have to update the lib minor version number, to `1.3.70` this time.

2021-11-19 05:18 UTC, chauchausoup commented
Lets follow the whiteboard while versioning from now. 
https://github.com/0chain/js-client-sdk/issues/65

2021-11-19 05:51 UTC, chauchausoup commented
Also what do you think about the other [X-App-Timestamp](https://github.com/0chain/js-client-sdk/blob/ff1c43a00d5b45f0c976d55cc88b390653c23b47/utils.js#L226) requests in the utils.js for example.

2021-11-19 06:24 UTC, chauchausoup commented
Also the server to which the http://worldtimeapi.org/api/timezone/Europe/London api is serving from might have limits and might show issues in the future. We should have our own timestamp server for uniformity. Please read here : http://worldtimeapi.org/pages/faqs#what-can-i-use-it-for

2021-11-20 20:29 UTC, shaktals commented
I have created a [discussion on slack](https://0chain.slack.com/archives/C01U94VF56Y/p1637440115140700) about this.

2021-11-22 16:09 UTC, Sarthakbunny commented
I'm not able to see the slack discussion, just proposing here to use the server date itself in every API rather than `new Date()` for every user.
CC: @chauchausoup @shaktals

2021-11-22 19:53 UTC, shaktals commented
@Sarthakbunny, the original issue on explorer has been updated by @Rizary with an 0chain issue that already has a `/server-time` PR associated. Please follow that issue, which will offer an API for us to solve this.

2021-12-06 20:01 UTC, shaktals requested changes

2021-12-06 20:01 UTC, shaktals commented on index.js
> +    const ts = Math.floor(new Date().getTime() / 1000 + serverDelay);
This whole logic can be extracted to another function, as it might be used by other functions, and is just a helper to `submitTransaction`. We could have something like:

```
async function getTimestamp() {
  const minutesSinceLastCheck = ...
  
  if (minutesSinceLastCheck >= 5)
    await this.updateLocalNetworkTimeDiff();

  const timestamp = Math.floor(new Date().getTime() / 1000 + localNetworkTimeDiff);
  return timestamp
}
```

2021-12-07 16:57 UTC, Sarthakbunny commented on index.js
> +        const { time } = await utils.getCurrentServerTime(url);
No @shaktals, was going to ask you on this one. Please give me some idea

2021-12-07 17:05 UTC, Sarthakbunny commented on index.js
> +    const lastServerTimeCheckDiff = Math.ceil(Math.abs(new Date() - lastServerTimeCheck)/(1000*60));
This is a time difference..... <, >= 5 min

2021-12-07 19:48 UTC, shaktals commented on index.js
> +        const { time } = await utils.getCurrentServerTime(url);
You can test it out, just meddle with the url at the axios call (like adding `09s0a9s` at the end of it.

2021-12-07 19:49 UTC, shaktals commented on index.js
> +        const { time } = await utils.getCurrentServerTime(url);
The `getTimestamp` function should be able to run successfully even if this fails (returning the time calculated against previously existing `localNetworkTimeDiff`).

2021-12-07 19:57 UTC, shaktals commented on index.js
> +    const lastServerTimeCheckDiff = Math.ceil(Math.abs(new Date() - lastServerTimeCheck)/(1000*60));
Got it. It was confusing at first. But I guess that if the local network time travels back into the past, the last check could be more than 5 minutes into the future, and then `Math.abs` would handle that case. Fun stuff :grinning:

2021-12-07 20:00 UTC, shaktals commented on index.js
> +        serverDelay = time - (new Date().getTime / 1000);
```suggestion
        localNetworkTimeDiff = time - (new Date().getTime / 1000);
```

2021-12-07 20:01 UTC, shaktals commented on utils.js
> +    getCurrentServerTime: function getCurrentServerTime(url) {
```suggestion
    getCurrentServerTime: function (url) {
```

2021-12-07 20:01 UTC, shaktals commented on index.js
> +var serverDelay = null;
@Sarthakbunny the first comment was not completely addressed.

2021-12-08 19:28 UTC, Sarthakbunny commented on utils.js
> +    getCurrentServerTime: function getCurrentServerTime(url) {
But this thing is common for all utils function

2021-12-09 21:17 UTC, shaktals requested changes
Please mark as 'resolved' the comments you have already addressed and pushed to repo.

2021-12-09 21:17 UTC, shaktals commented on index.js
> +        this.updateTimeDelay();
typo

2021-12-21 02:13 UTC, shaktals approved these changes

2021-12-21 02:14 UTC, merged