add wasm.js to bind wasm sdk
0chain/js-client-sdk pull request #73
Opened 2021-11-30 14:12 UTC by cnlangzi

2021-11-30 19:36 UTC, shaktals commented
One ugly thing about `js-client-sdk` is it's bad formatting.
Since we are starting `wasm.js` from scratch, I ran prettier over it.
Then I extracted logic too nested, simplified some returns, also for readability.
I'll now try to understand the general logic and comment the code.

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +  try {
In line with the above comment, we should not use try/catch, but let the lib throw the errors it finds. The client must be responsible for catching and handling.

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +      const msg = 'err: failed to sign';
The message can provide more context and be more descriptive.

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +	}
Do we need to check if the error is an `instanceof` Error? Even if it's only defined, it should be thrown.

```suggestion
	if (response.error instanceof Error)
	  throw response.error;
```

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +		},
It was somewhat confusing having blsSign try to read from bridge.bls.secretKey, until I saw that it refers to it's own parent object. For clarity, we should declare secretKey here, I suggest as null.

```suggestion
		bls: {
		    secretKey: null,
			sign: blsSign,
		},
```

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +	g.__zcn_wasm__ = {
Can we just call this `bridge`, it would be one less variable name to think about when trying to understand this.

```suggestion
if (!g.bridge) {
	g.bridge = {
```

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +          'Retrieved value from WASM returned function type, however called with arguments.'
```suggestion
          'Value retrieved  from WASM is not a function, however it was called with arguments.'
```

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +          'Retrieved value from WASM returned function type, however called with arguments.'
Should this be a case for rejection too?

2021-11-30 20:51 UTC, shaktals commented on wasm.js
> +  };
Do we really need to use a Proxy here? Feels like it makes things more complex that we'd probably need initially. Could we start more simple, and add complexity later if needed?

Always easy to add complexity, very hard to remove.

2021-11-30 23:27 UTC, shaktals commented on wasm.js
> +  };
I mention also because I took more than half an hour looking and rearranging the code to understand what was going on :see_no_evil:

2021-12-01 01:49 UTC, cnlangzi commented on wasm.js
> +    return msg;
this is function is designed for go. let me test if `throw error` is supported on go calback.

2021-12-01 01:59 UTC, cnlangzi commented on wasm.js
> +	}
`error` is not supported from go response.  need to double check it.

2021-12-01 02:00 UTC, cnlangzi commented on wasm.js
> +	}
```
// js.ValueOf returns x as a JavaScript value:
//
//  | Go                     | JavaScript             |
//  | ---------------------- | ---------------------- |
//  | js.Value               | [its value]            |
//  | js.Func                | function               |
//  | nil                    | null                   |
//  | bool                   | boolean                |
//  | integers and floats    | number                 |
//  | string                 | string                 |
//  | []interface{}          | new array              |
//  | map[string]interface{} | new object             |
//
// Panics if x is not one of the expected types.
```

2021-12-01 02:01 UTC, cnlangzi commented on wasm.js
> +	}
an object {error:""} as Error. BTW. wasm.js is designed for go. js features are not supported fully here. that is why I don't leave it with your team.

2021-12-01 12:51 UTC, cnlangzi commented on wasm.js
> +      const msg = 'err: failed to sign';
it is from bls_c.js. I am not what is detail now. just leave it .

2021-12-01 12:52 UTC, cnlangzi commented on wasm.js
> +	g.__zcn_wasm__ = {
`g.__zcn_wasm__` is called by go. bridge is short for js.

2021-12-01 12:53 UTC, cnlangzi commented on wasm.js
> +          'Retrieved value from WASM returned function type, however called with arguments.'
ignore it. it is just warning. it still works for getting property

2021-12-01 12:57 UTC, cnlangzi commented on wasm.js
> +  };
We need proxy to dynamically detect if go instance is ready or exited. and all wasm methods will be registered to __zcn_wasm__.sdk on runtime. so just leave it.

2021-12-01 23:35 UTC, shaktals commented on wasm.js
> +    return msg;
Do you mean `blsSign`? It totally looks like it'll be used by the client.
I don't see it being called by the sdk anywhere, not even on `setWallet`.

2021-12-01 23:49 UTC, shaktals commented on wasm.js
> +        throw err;
If we are going to throw, we better throw a proper Error instance. It's much friendlier to clients:

```suggestion
        const errMsg = 'err: bls.secretKey is not initialized';
        console.error(errMsg);
        throw new Error(errMsg);
```

2021-12-01 23:49 UTC, shaktals commented on wasm.js
> +        throw err;
Same applies everywhere else.

2021-12-01 23:49 UTC, shaktals commented on wasm.js
> +        throw err
```suggestion
        const errMsg = 'err: wasm blsSign function failed to sign transaction';
        console.error(errMsg);
        throw new Error(errMsg);
```

2021-12-01 23:49 UTC, shaktals commented on wasm.js
> +                rej(resp.error);
It will be nice to follow the same pattern used on line 114:

```suggestion
                rej(new Error(resp.error));
```

2021-12-01 23:49 UTC, shaktals commented on wasm.js
> +	}
The response comes from Go. But the handling of it has nothing to do with Go. This is pure javascript, no mystery about it.

2021-12-01 23:50 UTC, shaktals commented on wasm.js
> +	}
The error will be thrown for the client, after the Go function has run.

2021-12-01 23:54 UTC, shaktals commented on wasm.js
> +  };
I understand it can be done using proxy. But it can be done without it 100% too.
Anyways, not a big deal. After extracting each prop it became clearer what was going on.

2021-12-02 00:02 UTC, shaktals reviewed
One essential question that could maybe simplify this a lot. Can't we just sign the transaction here on the lib, as it was being done beofre?

That instead of doing the juggling to set the wallet within wasm so it can generate the signature there.

2021-12-02 00:02 UTC, shaktals commented on index.js
> +        zcn = await wasm.create();
It will only happen on first load, but it is a hell of a bad practice to make the user wait for dozens of seconds (depending on network) before the app is even rendered.

Because today the explorer still needs `js-client-sdk` initialized before the first screen paint.

2021-12-02 00:28 UTC, cnlangzi commented on index.js
> +        zcn = await wasm.create();
updated it to load wasm and init sdk in async thread.

2021-12-02 00:32 UTC, cnlangzi commented
> One essential question that could maybe simplify this a lot. Can't we just sign the transaction here on the lib, as it was being done beofre?
> 
> That instead of doing the juggling to set the wallet within wasm so it can generate the signature there.

in gosdk, any http request need to set header for wallet first, and send them back to bls.js to sign transaction. we have to change a lot of code to move http request stuff to js.
I think almost things will be migrated to wasm sdk too. blobber methods are migrated first. so I would suggest to leave it for now.

2021-12-02 00:37 UTC, cnlangzi commented
BTW. README.md is added on https://github.com/0chain/gosdk/blob/fix/hermui_on_wasm/wasmsdk/README.md

2021-12-02 01:06 UTC, shaktals commented
I just spoke to Saswata about the signing issue and realized that constraint was not introduced by the new wasm Go code, but it was already there before. So, yeah, unthinkable to mess with that.

2021-12-02 01:10 UTC, shaktals commented on index.js
> +        zcn = await wasm.create();
It is not the go sdk initialization that is the issue, but [this line](https://github.com/0chain/js-client-sdk/pull/73/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R182):

`zcn = await wasm.create()`

Here is where the `wasm` binary will be fetched.

2021-12-02 01:11 UTC, cnlangzi commented
> I just spoke to Saswata about the signing issue and realized that constraint was not introduced by the new wasm Go code, but it was already there before. So, yeah, unthinkable to mess with that.

do you mean `bls and miracl` that alex and Andika migrated? if yes, unfortunately it doesn't work with blobber and sharder. check detail here https://github.com/0chain/gosdk/issues/294#issue-1049918518.  that is why we have to update it now

2021-12-02 01:11 UTC, shaktals commented on index.js
> +        zcn = await wasm.create();
If the `await` is removed, than we must guard from user calls to the not initialized methods/object.

2021-12-02 01:14 UTC, shaktals commented
> do you mean `bls and miracl` that alex and Andika migrated? if yes, unfortunately it doesn't work with blobber and sharder. check detail here [0chain/gosdk#294 (comment)](https://github.com/0chain/gosdk/issues/294#issue-1049918518). that is why we have to update it now

I just mean that we had the signing function working on `js-client-sdk` already, and that we could sign and send the signature to wasm/Go. But now I see that the whole go-sdk depends on having a wallet set. So, much easier to do the `setWallet` juggle here, than to mess with `go-sdk` old constraint.

2021-12-02 01:16 UTC, shaktals commented
PR is getting nice! Main thing is handling the async `wasm.create()`, then just some clean up. I'm off now and continue tomorrow.

2021-12-02 01:22 UTC, cnlangzi commented on wasm.js
> +    return msg;
it is called by go. if you want to know whole logic, you need to check https://github.com/0chain/gosdk/pull/309  too

2021-12-02 01:24 UTC, cnlangzi commented on wasm.js
> +	}
in our wasm sdk , {error:""} will be returned to js if any exception is thrown, if not , result is returned to js directly. please check wasmsdk too if you want to understand whole logic.

2021-12-02 01:27 UTC, cnlangzi commented on index.js
> +        zcn = await wasm.create();
please double check wasm.js again. loadWasm has been added, and it is execute as async. so `await wasm.create` will not block main thread

2021-12-02 01:29 UTC, cnlangzi commented on wasm.js
> +  };
ok. leave it with your team to refactor it after wasm is ready.

2021-12-02 01:31 UTC, cnlangzi commented on wasm.js
> +	}
let's leave it with your team in future improvement if there is better way for your development

2021-12-02 01:33 UTC, cnlangzi commented on wasm.js
> +    return msg;
`setWallet` is used on react hook , please check https://github.com/0chain/block-explorer/pull/501#issuecomment-984187131

2021-12-02 17:57 UTC, shaktals commented on index.js
> +        zcn = await wasm.create();
It's very bad to assume that the download will complete and initialization will be done in 10 seconds max. It's much better to remove await here and maintain it there. No point trying let the code there run while the `wasm` binary hasn't been fetched yet.

2021-12-03 12:03 UTC, cnlangzi commented on index.js
> +        zcn = await wasm.create();
10s is only for warning. it doesn't break anything. proxy still waiting it loaded completely.

2021-12-03 12:08 UTC, cnlangzi commented on index.js
> +        zcn = await wasm.create();
please check it again. setTimeout is only a warning.  api call is waiting with 2nd line that has `while and sleep`.

<img width="737" alt="Screen Shot 2021-12-03 at 20 05 52" src="https://user-images.githubusercontent.com/347651/144599920-06eac074-db57-4d6d-be47-6f051ff22e02.png">

2021-12-03 22:01 UTC, shaktals commented on index.js
> +        zcn = await wasm.create();
Got what you mean, I amended just a few details.

2021-12-03 22:15 UTC, shaktals commented
Cool, async initialization looks good.

Now, passing `addTransaction` to js-sdk would be a very bad pattern.

If the 'auto-commit' boolean flag passed to the wasm function is true, can't we include the _commit transaction_ `id/hash` on the deleteResponse object returned by [this call](https://github.com/0chain/block-explorer/pull/501/files#diff-73c3b531393483c3ef052e483224912f0d0be4ea0e2957ace0d3f9f730c933a0R386-R391)?

2021-12-03 22:31 UTC, cnlangzi commented
> this call

It is implemented in two different thread. let me try to contact them. I will keep you update

2021-12-06 09:15 UTC, cnlangzi commented
@shaktals  could you leave wasm.js with me if you want to change any variable names. wasm sdk will crash if some variable name is changed.

2021-12-07 00:52 UTC, shaktals commented
> @shaktals could you leave wasm.js with me if you want to change any variable names. wasm sdk will crash if some variable name is changed.

I looked at the Go code and I knew it. Still, using just `js` for the prop name is very vague, does not clarify much for any developer that will look at this in the future. Here is a [good article](https://www.informit.com/articles/article.aspx?p=131025&seqNum=3) talking about it.

2021-12-07 00:55 UTC, shaktals requested changes
It seems like you code editor is indenting the `wasm.js` code with 4 spaces. Please fix. Standard prettier formatting for javascript is having just 2 spaces indentation. It's better to read, saves spaces horizontally and in many people's opinion is better aesthetically too.

2021-12-07 00:55 UTC, shaktals commented on index.js
> +        const resp = await goWasm.sdk.delete(allocation_id, path, commit);
When reading 'commit' parameter, I soon thought of a hash.
Took me several seconds to remember that this is a flag.
The variable name should reflect that, much easier to understand the method.

```suggestion
    deleteObject: async function (allocation_id, path, shouldAutoCommit) {
        const resp = await goWasm.sdk.delete(allocation_id, path, shouldAutoCommit);
```

2021-12-07 00:55 UTC, shaktals commented on wasm.js
> +    go.run(result.instance);
This way you can discount the time it took for the wasm binary to be fetched, which can vary greatly.

```suggestion
    const result = await WebAssembly.instantiateStreaming(
        await fetch('/zcn.wasm'),
        go.importObject
    );
    
    setTimeout(() => {
        if (bridge.__wasm_initialized__ !== true) {
            console.warn(
                'wasm bridge (zcn.__wasm_initialized__) still not true after max time'
            );
        }
    }, maxTime);
    
    go.run(result.instance);
```

2021-12-07 00:55 UTC, shaktals commented on wasm.js
> +};
```suggestion
};

```

2021-12-07 05:26 UTC, cnlangzi commented
> > @shaktals could you leave wasm.js with me if you want to change any variable names. wasm sdk will crash if some variable name is changed.
> 
> I looked at the Go code and I knew it. Still, using just `js` for the prop name is very vague, does not clarify much for any developer that will look at this in the future. Here is a [good article](https://www.informit.com/articles/article.aspx?p=131025&seqNum=3) talking about it.

renamed it with `jsProxy` on `wasm.js` and `zcn.wasm`

2021-12-07 05:32 UTC, cnlangzi commented
> It seems like you code editor is indenting the `wasm.js` code with 4 spaces. Please fix. Standard prettier formatting for javascript is having just 2 spaces indentation. It's better to read, saves spaces horizontally and in many people's opinion is better aesthetically too.

done

2021-12-07 13:52 UTC, cnlangzi commented on index.js
> +    goWasm.js.secretKey = blsSecret
```suggestion
goWasm.jsProxy.secretKey = blsSecret;
```

2021-12-07 19:13 UTC, shaktals approved these changes
Nice!! We still have a lot to improve on `js-client-sdk`, but the initial wasm implementation looks good. Let's test it out!

2021-12-14 19:29 UTC, merged